# Generated by Django 5.2.15 on 2026-06-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('grading', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('route', models.CharField(blank=True, choices=[('RESELL', 'Resell as-is'), ('REFURBISH', 'Refurbish & resell'), ('P2P', 'Peer-to-peer exchange'), ('DONATE', 'Donate')], max_length=10)),
                ('decided_by', models.CharField(blank=True, choices=[('llm', 'LLM'), ('ev', 'Expected value')], max_length=8)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('ev_route', models.CharField(blank=True, choices=[('RESELL', 'Resell as-is'), ('REFURBISH', 'Refurbish & resell'), ('P2P', 'Peer-to-peer exchange'), ('DONATE', 'Donate')], max_length=10)),
                ('llm_route', models.CharField(blank=True, choices=[('RESELL', 'Resell as-is'), ('REFURBISH', 'Refurbish & resell'), ('P2P', 'Peer-to-peer exchange'), ('DONATE', 'Donate')], max_length=10)),
                ('costs', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('assessment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_decision', to='grading.gradingassessment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_decisions', to='marketplace.order')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_decisions', to='catalog.itemunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('cash_refund', models.PositiveIntegerField(default=0, help_text='₹')),
                ('green_credits', models.PositiveIntegerField(default=0)),
                ('expected_loss', models.PositiveIntegerField(default=0, help_text='₹ loss avoided')),
                ('company_cost', models.PositiveIntegerField(default=0, help_text='₹ cost to company')),
                ('message', models.CharField(blank=True, max_length=300)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_offers', to='marketplace.order')),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='rerouting.routedecision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='routedecision',
            index=models.Index(fields=['order', 'status'], name='rerouting_r_order_i_9d9b68_idx'),
        ),
        migrations.AddIndex(
            model_name='routedecision',
            index=models.Index(fields=['-created_at'], name='rerouting_r_created_67b32b_idx'),
        ),
        migrations.AddIndex(
            model_name='returnoffer',
            index=models.Index(fields=['order', 'status'], name='rerouting_r_order_i_1231d6_idx'),
        ),
    ]
